# render.yaml
services:
  - type: web
    name: OpenAI-Test
    env: python
    plan: free          
    region: oregon 
    branch: main

    autoDeploy: true

    buildCommand: |
      pip install -U pip
      pip install -r requirements.txt

    startCommand: |
      gunicorn product_analyzer.wsgi:application --bind 0.0.0.0:$PORT --workers 2
      
