# Generated by Django 5.2.6 on 2025-09-30 08:15

import analyzer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=analyzer.models.upload_to, verbose_name='商品圖片')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='商品名稱')),
                ('description', models.TextField(blank=True, verbose_name='商品介紹')),
                ('recommended_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='推薦售價')),
                ('analysis_json', models.JSONField(blank=True, null=True, verbose_name='完整分析結果')),
                ('analyzed', models.BooleanField(default=False, verbose_name='已分析')),
            ],
            options={
                'verbose_name': '商品圖片',
                'verbose_name_plural': '商品圖片',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
