# Generated by Django 5.2.6 on 2025-10-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='story_content',
            field=models.TextField(blank=True, verbose_name='產品故事'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='story_generated',
            field=models.BooleanField(default=False, verbose_name='已生成故事'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='story_prompt',
            field=models.TextField(blank=True, verbose_name='使用者故事指令'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='story_style',
            field=models.CharField(blank=True, max_length=50, verbose_name='故事風格'),
        ),
    ]
